/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simple API
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Get all users
 */
export const getUsersResponseItem = zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional()
})
export const getUsersResponse = zod.array(getUsersResponseItem)

